### PR TITLE
fix: [codegeex] build can't import QPainterPath class

### PR DESCRIPTION
**Pull request by Yurii-huang**
image

### CODE REVIEW

**Comment by Yurii-huang** [comment]
@deepin-mozart

**Comment by Yurii-huang** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Review by Yurii-huang — COMMENTED** [review]
@deepin-mozart

**Comment by deepin-mozart** [comment]
> @deepin-mozart

image
提交日志要有body  @Yurii-huang

**Review by deepin-mozart — APPROVED** [review]

**Pull request merged**
